version: '3.7'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=pass123
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    image: leolazz/parttimedev-backend:2.0
    environment:
      - DATABASE_USER=postgres
      - POSTGRES_PASSWORD=pass123
      - DATABASE_NAME=parttimedev
      - DATABASE_PORT=5432
      - DATABASE_HOST=postgres
    command: npm run start:prod
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - '.:/app'
      - '/app/node_modules'
